OWASP/OpenCRE

.gitignore, README.md, webpack.config.js
- Replacing ~ done and not done with tick boxes
- Replace inline code commands with separate boxes, used <pre> instead of ``` as VSC shows it by default correct in the preview
- Added a git ignore for venv-* as I label my venv's ( getting weird errors because you're in the venv of another project has happened to often to me )
-  Added the copy of database command so users that see the project won't get errors because of an empty database
=> Small README styling changes for readability

application/frontend/src/components/DocumentNode/DocumentNode.tsx, application/frontend/src/pages/CommonRequirementEnumeration/CommonRequirementEnumeration.tsx, application/frontend/src/pages/Search/components/BodyText.tsx, application/frontend/src/pages/Standard/StandardSection.tsx, application/frontend/src/pages/Standard/standard.scss, application/frontend/src/routes.tsx, application/frontend/src/utils/document.ts, application/web/web_main.py, webpack.config.js
FIX #81
- Excluded document with 'contains' type from the nested views
- Added a separate text for external URL (i.e. the buttons will no longer link to external sources, now the URL will be shown on the page of the topic itself or if shown in a nested way)
- Added separate pages for sections of a standard
All standards, CRE's and sections of standards have their own page now.
=> #81 : remove contains from nested view and add clickable links for each cre

application/frontend/src/components/DocumentNode/DocumentNode.tsx, application/web/web_main.py
Fix #87
- Add nesting for link type "related"
- Topics nested in linktype "related" should only contain "linked" linkType (i.e. not contains / related / is part of)
- When there are no links available for a topic we'll not show it as a dropdown, as there are no links to show ( e.g. if a topic is nested in an "is related" linktype and only contains other links with "contains" or "is part of" as link types, which should not be shown as described in #87 and #81 ).
NOTE: we might want to do the retrieval of nested documents in the backend, now it fires 15+ requests for retrieving the nested documents ( depending on how many documents it links to ). Which is not ideal, but it works ;)
=> 87 mitigate cyclic nesting when related topic are nested

application/frontend/src/App.tsx, application/frontend/src/app.scss, application/frontend/src/index.html, application/frontend/src/pages/Search/components/BodyText.scss, application/frontend/src/pages/Search/components/SearchBar.scss, application/frontend/src/pages/Search/search.scss, application/frontend/src/pages/Standard/standard.scss, application/frontend/src/scaffolding/Header/header.scss
Adds visual fixes for the landing page in mobile, as well as various other small visual fixes on other pages.
fixes #31 
Specific items fixed:
- landing page content was not spanning the entire width on mobile (css resets added, removed some overrides etc)
- landing page content was too "thin" on mobile
- links on search results were overflowing container - added word wrapping
- issues with search bar on 2nd page (was overflowing off the screen) on mobile
left is before, right is after.
=> Visual fixes for mobile view (#31)

application/frontend/src/const.ts, application/frontend/src/pages/Search/SearchName.tsx, application/frontend/src/pages/Search/components/BodyText.tsx, application/frontend/src/pages/Search/components/SearchBar.tsx, application/frontend/src/pages/Search/components/SearchResults.tsx, application/frontend/src/routes.tsx
Fixes the forced window reload that was needed for the searched items to be reloaded.
Minor nits and other refactors and some minor reformatting here and there.
fixes (#83) 
- `SearchName.tsx` - this is the most interesting component: what I've changed was to add searchTerm as a dependency of useEffect, which triggers the network call to be made again, hence repopulating the list on results ; renamed `documentsToRender` to `results`, and extracted search results outside the file.
- `SearchBar.tsx` - minor refactor on the way we were storing the SEARCH_TYPES. so that it's easier to immediately reference any related value (in our case the path).
- also moved paths into an existing const file from the routes file
=> Fixes reload hack

application/cmd/cre_main.py, application/database/db.py, application/tests/capec_parser_test.py, application/utils/external_project_parsers/capec_parser.py, cre.py
add command line option --capec_in and relevant parser which downloads the latest capec xml from "https://capec.mitre.org/data/xml/capec_latest.xml", parses the attack patterns and for the ones we have known CWE ids , links them to CREs.
If there are no known CWE ids related to a CAPEC entry, an error is printed and the parsing continues silently adding a non-linked entry
=> Parse capec

.github/workflows/auto-import.yml, Makefile, application/utils/spreadsheet_parsers.py
this is a small but important one:
=> Fix cheatsheet import

application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx
Based on #377 (needs that merged first)
=> Minimal ga style

application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx
=> Make Direct Dark Green

application/frontend/src/const.ts, application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx, application/frontend/src/scaffolding/Header/Header.tsx, application/web/web_main.py
=> Rename gap to map

application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx, application/frontend/src/utils/document.ts
Use internal link function rather than bad template
=> GA fix bad links

application/database/db.py
Experiment to use allShortestPaths over shortestPath
At the cost of a noticeable longer load time we do get more results with allShortestPaths eg (http://localhost:9001/map_analysis?base=ASVS&compare=NIST%20800-53%20v5 first result returns 23 more results with allShortestPaths)
=> Use allShortestPaths over shortestPath

application/database/db.py, application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx
Fixes #425 
Bonus Fix: Using share link loading wouldn't show for GA loading because standards loading had finished (made them independent)
=> Added Cross-cutting concerns to GA blacklist

CONTRIBUTING.md
closes #460 by including language around PR to Issue mapping on contributing.md
=> add pr info to contributing guidelines

application/utils/external_project_parsers/juiceshop.py
Since v16.x the new Score Board with its generic `searchQuery=` parameter is available and the default in Juice Shop. While `challenge=` is still working as an alias for now, it will likely be removed in release v17.x. See here for new syntax: https://pwning.owasp-juice.shop/companion-guide/latest/part4/integration.html#_generating_links_to_juice_shop
=> Switch to new challenge search syntax

.github/workflows/e2e.yml, Dockerfile-dev, Makefile, Procfile, application/frontend/src/hooks/useEnvironment.ts, application/frontend/src/test/basic-e2e.test.ts, application/web/web_main.py
This reverts commit e5929f511e40db6c161b0c37841b8588e53f3e54.
=> Revert "backend runs on 5001 (#495)"

application/frontend/src/pages/Explorer/explorer.scss, application/frontend/src/pages/Explorer/explorer.tsx
Closes https://github.com/OWASP/OpenCRE/issues/492
This PR contains a style change to make /explorer look like the original https://zeljkoobrenovic.github.io/opencre-explorer/:
Updated style:
=> Issue 492: Style update for the explorer

application/frontend/src/utils/document.ts
[Ticket](https://github.com/OWASP/OpenCRE/issues/508)
This is a tiny bugfix to ensure that links of type "Autolinked To" show on the CRE details page:
=> [ticket-508] Ensure autolinks appear on the CRE page

application/frontend/src/hooks/useLocationFromOutsideRoute.tsx, application/frontend/src/pages/BrowseRootCres/browseRootCres.scss, application/frontend/src/pages/BrowseRootCres/browseRootCres.tsx, application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx, application/frontend/src/pages/Search/Search.tsx, application/frontend/src/pages/Search/components/BodyText.tsx, application/frontend/src/pages/Search/components/SearchBar.scss, application/frontend/src/pages/Search/search.scss, application/frontend/src/routes.tsx, application/frontend/src/scaffolding/Header/Header.tsx, application/frontend/src/scaffolding/Header/header.scss
[Ticket](https://github.com/OWASP/OpenCRE/issues/502)
This PR updates the style and content of the main navigation.
**Changes**:
- add a new main nav link: "Browse"
- style the header and show it on the home page too. Remove the search from the header only on the home page, to avoid duplication.
- add "OR" to the homepage to separate Browse from Search
- adjust page titles (Root CREs and Map Analysis)
- tweak the margins and padding on the pages, so they align with the logo nicely
- Style the header for mobile
**Screenshots**
=> Feature/502 Update the header and main navigation

application/frontend/src/pages/Explorer/explorer.scss, application/frontend/src/pages/Explorer/explorer.tsx, application/frontend/src/pages/GapAnalysis/GapAnalysis.scss, application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx, application/frontend/src/pages/Search/search.scss, application/frontend/src/scaffolding/Header/header.scss
[Ticket](https://github.com/OWASP/OpenCRE/issues/511)
This PR adjusts the styles for the homepage and fixes a few style issues on mobile:
- make the home banner and Browse button smaller
- remove white bar on the homepage on mobile
- reduce space between the menu items on mobile
- centre the logo on mobile
- adjust the header style on tablet
- change the padding on the Explorer page to match the other pages, also tweak the search label and the sub-menu.
- align the labels on Map Analysis
- resolve a browser warning on the Map Analysis page by moving a warning message out of the table.
=> [511] UI-only: Adjust homepage banner height and fix style issues on mobile

application/frontend/src/components/FilterButton/FilterButton.tsx, application/frontend/src/hooks/applyFilters.tsx, application/frontend/src/pages/CommonRequirementEnumeration/CommonRequirementEnumeration.tsx, application/frontend/src/pages/Explorer/LinkedStandards.scss, application/frontend/src/pages/Explorer/LinkedStandards.tsx, application/frontend/src/pages/Explorer/explorer.scss, application/frontend/src/pages/Explorer/explorer.tsx
[Ticket](https://github.com/OWASP/OpenCRE/issues/507)
This PR makes it so that the standards on the /explorer page now link to the filtered CRE page filtered by them.
For example:
1. A CRE has links to all of these standards: 
2. You click on NIST 
3. You get the CRE page showing the NIST sections that are related to that CRE: 
4. If the link is to an ungrouped standard and has an external link, you would be linked directly to that page:
=> [507] UI-only: Link standard tags in /explorer directly to the right entries for the CRE

application/frontend/src/pages/Explorer/LinkedStandards.tsx, application/frontend/src/pages/Explorer/explorer.tsx, application/frontend/src/providers/DataProvider.tsx
[Ticket](https://github.com/OWASP/OpenCRE/issues/514)
This PR ensures that all leaf CREs are also included in the explorer. Previously if a link was in the keypath of the tree traversal it was excluded. This is fine for nodes, but was causing a bug for leaves.
The fix apples to the /explorer and the Graph. They should now include all linked CREs:
=> Bugfix/514 :bug: Fix explorer incomplete

application/frontend/src/pages/Explorer/explorer.tsx, application/frontend/src/providers/DataProvider.tsx
[Issue](https://github.com/OWASP/OpenCRE/issues/515)
This PR ensures that the loading animation displays while the UI fetches data from the API. The fix uses the React "useQuery" attribute for `isLoading`:
=> [515] :wrench: Explorer - fix loading indicator

README.md, application/__init__.py, application/frontend/src/providers/DataProvider.tsx, application/web/web_main.py, cre.py, requirements.txt
=> Removed: opentelemetry

requirements.txt
The CI run was failing [here](https://github.com/OWASP/OpenCRE/actions/runs/10183980036/job/28170207299?pr=542) because of missing Python click package. This PR adds it. That doesn't resolve the issue, I'll investigate further
=> :wrench: Failing CI - add missing Python 'click' package

application/prompt_client/prompt_client.py, application/prompt_client/vertex_prompt_client.py, requirements.txt
The chatbot was relying on ancient palm2 Bison models.
Google deprecated them a while ago in favour of gemini.
To fix that we upgraded the library and the models and changed the api to use the new sdk
=> fix chatbot

application/frontend/src/pages/Explorer/visuals/circles/circles.tsx, application/frontend/src/pages/Explorer/visuals/force-graph/forceGraph.tsx, application/frontend/src/scaffolding/Header/Header.tsx
This PR is related to ticket #514  
1- In explorer , I have checked and Made sure that all CREs and Standards are rendered correctly on the frontend . - See the solution through the last commit by @dlicheva (https://github.com/OWASP/OpenCRE/pull/542) 
2- For Circular Graph , I have added an edge condition for displayName -
Genrated Graph - 
3- Similairy here for Force_graph I have added an edge condition for `reduce()` array.
=> Changes in Explorer and Visual Graphs

application/frontend/src/pages/Explorer/visuals/circles/circles.scss, application/frontend/src/pages/Explorer/visuals/circles/circles.tsx
@robvanderveer @northdpole @paoga87 
As mentioned in the ticket #619 , here the changes made in the Zoomable Circles -- 
1) Changes the name from "Cluster" --> "OpenCRE" 
2) Increased the Zoom-in/out scale from "0.8" --> "2.4" (3 times) 
3) - Solved the resizing problem --> Cause = D3 circles don't resize with the browser window because the drawing logic within the useEffect hook is not re-running when the window dimensions change --> Solution = Moved size  outside the useEffect and added it to dependency 
4) Enabled the labels and made then render at the top of the circle
Demonstrating video - 
https://github.com/user-attachments/assets/75833037-6fa4-4517-a545-1469ae338e14
Extra changes discussed  After this -- 
1)- Removed the child count 
2)- Removed the Prefix "CRE" and also the …
=> Fixed ticket #619 - Changes in Zoomable -Circles (Parth)
