OWASP/OpenCRE

- application/config.py
- application/web/web_main.py
> Force https

- application/__init__.py
- application/config.py
- application/web/web_main.py
- requirements.txt
> enable cache for prod

- application/__init__.py
- requirements.txt
> add compression

- application/frontend/src/pages/Search/Search.tsx
- application/frontend/src/pages/Search/components/BodyText.tsx
- application/frontend/src/pages/Search/search.scss
Updated the conent.
Still to do:
- add logo
> Partial fix for #31 : Improve the landing page content and look

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- Makefile
- README.md
- application/web/web_main.py
- jest.config.js
> add makefile, add contributing instructions and readme improvements

- application/frontend/src/components/DocumentNode/DocumentNode.tsx
- application/frontend/src/pages/CommonRequirementEnumeration/CommonRequirementEnumeration.tsx
- application/frontend/src/pages/Search/SearchName.tsx
- application/frontend/src/pages/Search/components/SearchBar.tsx
- application/frontend/src/routes.tsx
- application/frontend/src/utils/document.ts
- application/frontend/src/utils/index.ts
Backend also returns matching Standards, so made two columns in the search matches ( one for CRE and other one for Standards ).
> FIX 39 search frontend

- application/frontend/src/pages/Search/components/SearchBar.tsx
- application/web/web_main.py
dirty fix to lower the priority of #83
> fix search function on results page, horrible hack, hopefully temporary

- application/database/db.py
- application/tests/parsers_test.py
- application/utils/parsers.py
- application/web/web_main.py
> parse v2.1 and change tags behaviour

- application/frontend/src/pages/Deeplink/Deeplink.tsx
- application/frontend/src/routes.tsx
> fix deeplink

- application/database/db.py
- application/frontend/src/const.ts
- application/frontend/src/pages/BrowseRootCres/browseRootCres.scss
- application/frontend/src/pages/BrowseRootCres/browseRootCres.tsx
- application/frontend/src/routes.tsx
- application/tests/db_test.py
- application/web/web_main.py
quicken browsing for root CREs by providing a shortcut dedicated method for it
> quicken browsing for root CREs

- .devcontainer/devcontainer.json
- .gitignore
- yarn.lock
> add more options to devcontainer

- application/frontend/src/pages/CommonRequirementEnumeration/CommonRequirementEnumeration.tsx
- application/frontend/src/utils/document.ts
closes https://github.com/OWASP/common-requirement-enumeration/issues/237
> fix the link order of CRE link categories on a CRE page

- application/frontend/src/components/DocumentNode/DocumentNode.tsx
- application/frontend/src/components/DocumentNode/documentNode.scss
> Add: Clearer document seperations

- application/frontend/src/components/DocumentNode/DocumentNode.tsx
- application/frontend/src/components/DocumentNode/documentNode.scss
> Reference link for simple node views

- application/frontend/src/components/DocumentNode/DocumentNode.tsx
- application/frontend/src/pages/CommonRequirementEnumeration/CommonRequirementEnumeration.tsx
- application/frontend/src/pages/Standard/StandardSection.tsx
> Replaced:  duplicate  display name with "Which"

- application/frontend/src/components/DocumentNode/DocumentNode.tsx
- application/frontend/src/components/DocumentNode/documentNode.scss
- application/frontend/src/pages/CommonRequirementEnumeration/CommonRequirementEnumeration.tsx
- application/frontend/src/pages/CommonRequirementEnumeration/commonRequirementEnumeration.scss
- application/frontend/src/pages/Search/components/SearchResults.tsx
> Clean up nested document node splits

- application/frontend/src/components/DocumentNode/DocumentNode.tsx
> Return Color CRE separation (more suitable color this time)

- application/frontend/src/pages/MembershipRequired/MembershipRequired.scss
- application/frontend/src/pages/MembershipRequired/MembershipRequired.tsx
- application/frontend/src/routes.tsx
> Added: Membership required page with OWASP link

- application/frontend/src/pages/Search/components/BodyText.tsx
> Add CRE Chatbot heading

- application/frontend/src/pages/BrowseRootCres/browseRootCres.scss
> Make links gaps same size as nested gaps

- application/frontend/src/components/DocumentNode/DocumentNode.tsx
- application/frontend/src/const.ts
- application/frontend/src/pages/Standard/StandardSection.tsx
- application/frontend/src/utils/document.ts
Fixes: #336
Assuming its just Standard -> CRE for custom text
> Added custom type text for standard -> CRE

- application/frontend/src/pages/BrowseRootCres/browseRootCres.tsx
> Remove duplciate Root CREs

- application/cmd/cre_main.py
- application/database/db.py
- application/tests/db_test.py
- application/utils/gap_analysis.py
- cre.py
> Disable auto db pop

- application/frontend/src/pages/chatbot/chatbot.tsx
- application/prompt_client/openai_prompt_client.py
- application/prompt_client/prompt_client.py
- application/prompt_client/vertex_prompt_client.py
> #368 generic llm fallback

- application/frontend/src/pages/chatbot/chatbot.tsx
> fix bug where timestamps where getting regenerated

- application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx
> Fix: GA share link spaces

- application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx
> Added: Direct link grade and removed external link icon

- application/database/db.py
- application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx
- application/frontend/src/types.ts
- application/tests/gap_analysis_test.py
- application/utils/gap_analysis.py
> Link improvements

- application/web/web_main.py
> Fix: GA caching not taking queries

- application/utils/gap_analysis.py
> GA Reduce related punishment

- application/frontend/src/pages/GapAnalysis/GapAnalysis.tsx
> Sort Base standard alphabetically

- application/database/db.py
- application/frontend/src/App.tsx
- application/frontend/src/components/LoadingAndErrorIndicator/LoadingAndErrorIndicator.tsx
- application/frontend/src/pages/Explorer/explorer.tsx
- application/frontend/src/providers/DataProvider.tsx
- application/tests/db_test.py
- application/tests/web_main_test.py
- application/web/web_main.py
> paginate graph retrieval init

- .gitignore
- application/frontend/src/providers/DataProvider.tsx
- application/web/web_main.py
[Issue](https://github.com/OWASP/OpenCRE/issues/514)
This PR ensures that the explorer tree is fully build, while only including "Contains" relationships.
> [514] :bug: Fix explorer incomplete

- docs/developmentSetup.md
No other changes except are made other than required in the file
> Changes in DevelopmentSetup Doc related to  initialization of DB

- README.md
This comment will allow developers, testers, & contributors to run a local virtual machine environment using Python venv without setting up a devcontainer to run, develope, and test in an isolated environment.
> Update README.md with  recommended comment to run in Python Venv

- application/frontend/src/pages/Explorer/visuals/circles/circles.tsx
I have removed the artefacts which were visible on leaf nodes ..
Final result -->
> Fix : removed the visible line artefacts on the leafs

- application/frontend/src/pages/Explorer/visuals/circles/circles.tsx
Added the functionality , when the white leaf nodes (which have the hyperlinks) , will be clicked then the links will open themselves on the new tab .
key changes - 
1- Added styles to useEffect , that will figure out that whether it has hyperlink or not 
2- Extract the hyperlink field and then open it up on new tab 
Refer to the video below -- 
https://github.com/user-attachments/assets/2716ae9a-4bda-48c4-a955-ec287674a4a4
> Fix/circle graph - Added the functionality in which when it clicks the white nodes with hyperlinks , it will get open to new tab 
